# Generated by Django 5.1.4 on 2026-06-29 18:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_id', models.CharField(help_text='PUBG numeric Player ID supplied by the customer', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Payment Confirmed'), ('FULFILLED', 'UC Delivered'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('wholesaler_order_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name, e.g. '60 UC'", max_length=120)),
                ('sku', models.CharField(help_text="Wholesaler/region-specific SKU, e.g. 'PUBG_NG_60UC'", max_length=80, unique=True)),
                ('uc_amount', models.PositiveIntegerField(help_text='Number of UC this package grants')),
                ('price_ngn', models.DecimalField(decimal_places=2, help_text='Retail price in NGN (e.g. 750.00)', max_digits=12)),
                ('badge', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UC Package',
                'verbose_name_plural': 'UC Packages',
                'ordering': ['price_ngn'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_reference', models.CharField(help_text='Paystack transaction reference (globally unique)', max_length=120, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Confirmed amount in NGN', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting Verification'), ('SUCCESS', 'Verified Successful'), ('FAILED', 'Verification Failed')], default='PENDING', max_length=12)),
                ('paystack_access_code', models.CharField(blank=True, default='', max_length=120)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.product'),
        ),
    ]
