# Generated by Django 5.1.4 on 2026-06-29 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_seed_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User account linked to this order, if authenticated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SavedPlayerID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(help_text='PUBG numeric Player ID', max_length=30)),
                ('label', models.CharField(help_text="E.g. 'My Main Account', 'Second Profile'", max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_player_ids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Player ID',
                'verbose_name_plural': 'Saved Player IDs',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'player_id')},
            },
        ),
    ]
