# Generated by Django 5.0.7 on 2026-06-30 10:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_user_savedplayerid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('BOTH', 'Both Email and SMS')], default='EMAIL', max_length=10)),
                ('notification_type', models.CharField(choices=[('order_created', 'Order Created'), ('payment_confirmed', 'Payment Confirmed'), ('uc_delivered', 'UC Delivered'), ('order_failed', 'Order Failed'), ('refund_requested', 'Refund Requested'), ('refund_approved', 'Refund Approved'), ('refund_completed', 'Refund Completed')], db_index=True, max_length=50)),
                ('recipient', models.CharField(help_text='Email address or phone number', max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Send'), ('SENT', 'Successfully Sent'), ('FAILED', 'Failed'), ('QUEUED', 'Queued for Retry')], db_index=True, default='PENDING', max_length=12)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund amount in NGN', max_digits=12)),
                ('reason', models.TextField(help_text="Customer's reason for refund request")),
                ('status', models.CharField(choices=[('REQUESTED', 'Refund Requested'), ('APPROVED', 'Approved by Admin'), ('PROCESSING', 'Paystack Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], db_index=True, default='REQUESTED', max_length=12)),
                ('paystack_transfer_id', models.CharField(blank=True, default='', help_text='Paystack transfer recipient code or reference', max_length=120)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Internal notes from admin')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='savedplayerid',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'Saved Player ID', 'verbose_name_plural': 'Saved Player IDs'},
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, db_index=True, default='', help_text='Customer email for notifications (guest or registered user)', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='failure_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of fulfillment retry attempts'),
        ),
        migrations.AddField(
            model_name='order',
            name='failure_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for order failure (fulfillment/payment/etc)'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_soft_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for archival'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last retry attempt', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict, help_text='Extra tracking data (validation errors, user agent, etc)'),
        ),
        migrations.AddField(
            model_name='savedplayerid',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Mark as default for quick-select'),
        ),
        migrations.AddField(
            model_name='savedplayerid',
            name='is_valid',
            field=models.BooleanField(default=True, help_text='Flag set to False if PUBG API validation fails'),
        ),
        migrations.AddField(
            model_name='savedplayerid',
            name='last_validated_at',
            field=models.DateTimeField(blank=True, help_text='Last time Player ID was validated against PUBG API', null=True),
        ),
        migrations.AddField(
            model_name='savedplayerid',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='savedplayerid',
            name='validation_error',
            field=models.TextField(blank=True, default='', help_text='Error message from PUBG API validation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Payment Confirmed'), ('FULFILLED', 'UC Delivered'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=12),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_email', 'status'], name='orders_orde_custome_66d5e2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_soft_deleted', 'created_at'], name='orders_orde_is_soft_496a54_idx'),
        ),
        migrations.AddIndex(
            model_name='savedplayerid',
            index=models.Index(fields=['user', 'is_default'], name='orders_save_user_id_41c754_idx'),
        ),
        migrations.AddIndex(
            model_name='savedplayerid',
            index=models.Index(fields=['is_valid'], name='orders_save_is_vali_4f271a_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order'),
        ),
        migrations.AddField(
            model_name='refund',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['order', 'status'], name='orders_noti_order_i_c7e8ef_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'created_at'], name='orders_noti_status_01f7e9_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', 'requested_at'], name='orders_refu_status_ca5f04_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['order'], name='orders_refu_order_i_341cd7_idx'),
        ),
    ]
